//===============================================================================//
//
//      husb define
//
//===============================================================================//
#define husb_base(i)    (0xfd0000 + 0x1000*i)

#define husb_phy_com_sfr_ptr(num)   (*(volatile u32 *)(husb_base(0) + num*4))
#define husb_sie_sfr_ptr(num)       (husb_base(1) + num)
#define husb_ctl_sfr_ptr(num)       (*(volatile u32 *)(husb_base(2) + num*4))

#define HUSB_PLL_CON0                   husb_phy_com_sfr_ptr(0)
#define HUSB_PLL_CON2                   husb_phy_com_sfr_ptr(1)
#define HUSB_PLL_NR                     husb_phy_com_sfr_ptr(2)
#define HUSB_PHY0_CON0                  husb_phy_com_sfr_ptr(3)
#define HUSB_PHY0_CON1                  husb_phy_com_sfr_ptr(4)
#define HUSB_PHY0_CON2                  husb_phy_com_sfr_ptr(5)
#define HUSB_PHY0_CON3                  husb_phy_com_sfr_ptr(6)
#define HUSB_PHY0_CON4                  husb_phy_com_sfr_ptr(7)
#define HUSB_PHY0_READ                  husb_phy_com_sfr_ptr(8)
#define HUSB_PHY0_TSCON                 husb_phy_com_sfr_ptr(9)
#define HUSB_PHY0_TSCRC                 husb_phy_com_sfr_ptr(10)
#define HUSB_TRIM_CON0                  husb_phy_com_sfr_ptr(11)
#define HUSB_TRIM_CON1                  husb_phy_com_sfr_ptr(12)
#define HUSB_TRIM_PND                   husb_phy_com_sfr_ptr(13)
#define HUSB_FRQ_CNT                    husb_phy_com_sfr_ptr(14)
#define HUSB_FRQ_SCA                    husb_phy_com_sfr_ptr(15)

#define H0_FADDR                        (*(volatile u8  *)husb_sie_sfr_ptr(0x000))
#define H0_POWER                        (*(volatile u8  *)husb_sie_sfr_ptr(0x001))
#define H0_INTRTX                       (*(volatile u16 *)husb_sie_sfr_ptr(0x002))
#define H0_INTRRX                       (*(volatile u16 *)husb_sie_sfr_ptr(0x004))
#define H0_INTRTXE                      (*(volatile u16 *)husb_sie_sfr_ptr(0x006))
#define H0_INTRRXE                      (*(volatile u16 *)husb_sie_sfr_ptr(0x008))
#define H0_INTRUSB                      (*(volatile u8  *)husb_sie_sfr_ptr(0x00a))
#define H0_INTRUSBE                     (*(volatile u8  *)husb_sie_sfr_ptr(0x00b))
#define H0_FRAME                        (*(volatile u16 *)husb_sie_sfr_ptr(0x00c))
#define H0_INDEX                        (*(volatile u8  *)husb_sie_sfr_ptr(0x00e))
#define H0_TESTMODE                     (*(volatile u8  *)husb_sie_sfr_ptr(0x00f))
#define H0_FIFO0                        (*(volatile u8  *)husb_sie_sfr_ptr(0x020))
#define H0_FIFO1                        (*(volatile u8  *)husb_sie_sfr_ptr(0x024))
#define H0_FIFO2                        (*(volatile u8  *)husb_sie_sfr_ptr(0x028))
#define H0_FIFO3                        (*(volatile u8  *)husb_sie_sfr_ptr(0x02c))
#define H0_FIFO4                        (*(volatile u8  *)husb_sie_sfr_ptr(0x030))
#define H0_FIFO5                        (*(volatile u8  *)husb_sie_sfr_ptr(0x034))
#define H0_FIFO6                        (*(volatile u8  *)husb_sie_sfr_ptr(0x038))
#define H0_DEVCTL                       (*(volatile u8  *)husb_sie_sfr_ptr(0x060))
#define H0_EP0_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x080))
#define H0_EP0_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x082))
#define H0_EP0_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x083))
#define H0_EP0_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x084))
#define H0_EP0_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x086))
#define H0_EP0_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x087))
#define H0_EP1_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x088))
#define H0_EP1_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x08a))
#define H0_EP1_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x08b))
#define H0_EP1_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x08c))
#define H0_EP1_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x08e))
#define H0_EP1_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x08f))
#define H0_EP2_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x090))
#define H0_EP2_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x092))
#define H0_EP2_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x093))
#define H0_EP2_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x094))
#define H0_EP2_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x096))
#define H0_EP2_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x097))
#define H0_EP3_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x098))
#define H0_EP3_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x09a))
#define H0_EP3_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x09b))
#define H0_EP3_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x09c))
#define H0_EP3_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x09e))
#define H0_EP3_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x09f))
#define H0_EP4_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0a0))
#define H0_EP4_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0a2))
#define H0_EP4_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0a3))
#define H0_EP4_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0a4))
#define H0_EP4_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0a6))
#define H0_EP4_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0a7))
#define H0_EP5_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0a8))
#define H0_EP5_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0aa))
#define H0_EP5_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0ab))
#define H0_EP5_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0ac))
#define H0_EP5_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0ae))
#define H0_EP5_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0af))
#define H0_EP6_TXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0b0))
#define H0_EP6_TXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0b2))
#define H0_EP6_TXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0b3))
#define H0_EP6_RXFUNCADDR               (*(volatile u8  *)husb_sie_sfr_ptr(0x0b4))
#define H0_EP6_RXHUBADDR                (*(volatile u8  *)husb_sie_sfr_ptr(0x0b6))
#define H0_EP6_RXHUBPORT                (*(volatile u8  *)husb_sie_sfr_ptr(0x0b7))
#define H0_CSR0                         (*(volatile u16 *)husb_sie_sfr_ptr(0x102))
#define H0_COUNT0                       (*(volatile u16 *)husb_sie_sfr_ptr(0x108))
#define H0_NAKLIMIT0                    (*(volatile u8  *)husb_sie_sfr_ptr(0x10b))
#define H0_CFGDATA                      (*(volatile u8  *)husb_sie_sfr_ptr(0x10f))
#define H0_EP1TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x110))
#define H0_EP1TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x112))
#define H0_EP1RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x114))
#define H0_EP1RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x116))
#define H0_EP1RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x118))
#define H0_EP1TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x11a))
#define H0_EP1TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x11b))
#define H0_EP1RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x11c))
#define H0_EP1RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x11d))
#define H0_EP1FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x11f))
#define H0_EP2TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x120))
#define H0_EP2TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x122))
#define H0_EP2RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x124))
#define H0_EP2RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x126))
#define H0_EP2RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x128))
#define H0_EP2TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x12a))
#define H0_EP2TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x12b))
#define H0_EP2RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x12c))
#define H0_EP2RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x12d))
#define H0_EP2FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x12f))
#define H0_EP3TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x130))
#define H0_EP3TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x132))
#define H0_EP3RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x134))
#define H0_EP3RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x136))
#define H0_EP3RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x138))
#define H0_EP3TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x13a))
#define H0_EP3TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x13b))
#define H0_EP3RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x13c))
#define H0_EP3RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x13d))
#define H0_EP3FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x13f))
#define H0_EP4TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x140))
#define H0_EP4TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x142))
#define H0_EP4RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x144))
#define H0_EP4RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x146))
#define H0_EP4RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x148))
#define H0_EP4TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x14a))
#define H0_EP4TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x14b))
#define H0_EP4RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x14c))
#define H0_EP4RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x14d))
#define H0_EP4FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x14f))
#define H0_EP5TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x150))
#define H0_EP5TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x152))
#define H0_EP5RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x154))
#define H0_EP5RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x156))
#define H0_EP5RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x158))
#define H0_EP5TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x15a))
#define H0_EP5TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x15b))
#define H0_EP5RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x15c))
#define H0_EP5RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x15d))
#define H0_EP5FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x15f))
#define H0_EP6TXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x160))
#define H0_EP6TXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x162))
#define H0_EP6RXMAXP                    (*(volatile u16 *)husb_sie_sfr_ptr(0x164))
#define H0_EP6RXCSR                     (*(volatile u16 *)husb_sie_sfr_ptr(0x166))
#define H0_EP6RXCOUNT                   (*(volatile u16 *)husb_sie_sfr_ptr(0x168))
#define H0_EP6TXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x16a))
#define H0_EP6TXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x16b))
#define H0_EP6RXTYPE                    (*(volatile u8  *)husb_sie_sfr_ptr(0x16c))
#define H0_EP6RXINTERVAL                (*(volatile u8  *)husb_sie_sfr_ptr(0x16d))
#define H0_EP6FIFOSIZE                  (*(volatile u8  *)husb_sie_sfr_ptr(0x16f))
#define H0_RX_DPKTDIS                   (*(volatile u16 *)husb_sie_sfr_ptr(0x340))
#define H0_TX_DPKTDIS                   (*(volatile u16 *)husb_sie_sfr_ptr(0x342))
#define H0_C_T_UCH                      (*(volatile u16 *)husb_sie_sfr_ptr(0x344))

#define H0_SIE_CON                      husb_ctl_sfr_ptr(0x00)
#define H0_EP0_CNT                      husb_ctl_sfr_ptr(0x01)
#define H0_EP1_CNT                      husb_ctl_sfr_ptr(0x02)
#define H0_EP2_CNT                      husb_ctl_sfr_ptr(0x03)
#define H0_EP3_CNT                      husb_ctl_sfr_ptr(0x04)
#define H0_EP4_CNT                      husb_ctl_sfr_ptr(0x05)
#define H0_EP5_CNT                      husb_ctl_sfr_ptr(0x06)
#define H0_EP6_CNT                      husb_ctl_sfr_ptr(0x07)
#define H0_EP1_TADR                     husb_ctl_sfr_ptr(0x08)
#define H0_EP1_RADR                     husb_ctl_sfr_ptr(0x09)
#define H0_EP2_TADR                     husb_ctl_sfr_ptr(0x0a)
#define H0_EP2_RADR                     husb_ctl_sfr_ptr(0x0b)
#define H0_EP3_TADR                     husb_ctl_sfr_ptr(0x0c)
#define H0_EP3_RADR                     husb_ctl_sfr_ptr(0x0d)
#define H0_EP4_TADR                     husb_ctl_sfr_ptr(0x0e)
#define H0_EP4_RADR                     husb_ctl_sfr_ptr(0x0f)
#define H0_EP5_TADR                     husb_ctl_sfr_ptr(0x10)
#define H0_EP5_RADR                     husb_ctl_sfr_ptr(0x11)
#define H0_EP6_TADR                     husb_ctl_sfr_ptr(0x12)
#define H0_EP6_RADR                     husb_ctl_sfr_ptr(0x13)
#define H0_EP3_ISO_CON                  husb_ctl_sfr_ptr(0x14)
#define H0_EP4_ISO_CON                  husb_ctl_sfr_ptr(0x15)

//===============================================================================//
//
//      sfr endef
//
//===============================================================================//


