///**
// * @file tkl_thread.c
// * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
// *
// * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
// *           changes in other place will be overwrited and lost
// *
// * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
// *
// */
//
// --- BEGIN: user defines and implements ---
#include "tkl_thread.h"
#include "tuya_error_code.h"
#include "os_api.h"
// --- END: user defines and implements ---

/**
* @brief Create thread
*
* @param[out] thread: thread handle
* @param[in] name: thread name
* @param[in] stack_size: stack size of thread
* @param[in] priority: priority of thread,please ref to tkl thread priority define in tuya_cloud_types.h
* @param[in] func: the main thread process function
* @param[in] arg: the args of the func, can be null
*
* @note This API is used for creating thread.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_create(TKL_THREAD_HANDLE *thread,
                              CONST CHAR_T *name,
                              UINT_T stack_size,
                              UINT_T priority,
                              CONST THREAD_FUNC_T func,
                              VOID_T *CONST arg)
{
    // --- BEGIN: user implements ---
//    printf("thread_fork 创建线程任务成功");

    int ret;
    if (thread == NULL || name == NULL || func == NULL) {
        return OPRT_INVALID_PARM;
    }
    /* int pri = priority + 21; */
    /* if (pri > 30) { */
    /* pri = 30; */
    /* } */
    int *pid = (int *)malloc(sizeof(int));
    if (pid == NULL) {
        return OPRT_MALLOC_FAILED;
    }
    memset(pid, 0, sizeof(int));

    if (!strncmp((const char *)name, "sys_timer", 9)) {
        ret = thread_fork("ty_sys_timer", priority, (stack_size + 8 * 1024) / sizeof(int), 0, pid, (void (*)(void *))func, arg);
    } else {
        ret = thread_fork(name, priority, (stack_size + 8 * 1024) / sizeof(int), 0, pid, (void (*)(void *))func, arg);
    }

    /* int ret = thread_fork(name, priority, (stack_size + 8 * 1024) / sizeof(int), 0, pid, (void (*)(void *))func, arg); */
    if (ret != 0) {
        free(pid);
        return (OPERATE_RET)ret; // Assuming ret maps to OPERATE_RET
    }
    *thread = (TKL_THREAD_HANDLE)pid;
    //printf("thread_fork 创建线程任务成功");
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Terminal thread and release thread resources
*
* @param[in] thread: thread handle
*
* @note This API is used to terminal thread and release thread resources.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_release(CONST TKL_THREAD_HANDLE thread)
{
    // --- BEGIN: user implements ---
    // if (!thread) {
    //     return OPRT_INVALID_PARM;
    // }

    printf("kill thread！");
    int *pid = (int *)thread;
    thread_kill(pid, KILL_WAIT);
    free(pid);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Get the thread stack's watermark
*
* @param[in] thread: thread handle
* @param[out] watermark: watermark in Bytes
*
* @note This API is used to get the thread stack's watermark.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_get_watermark(CONST TKL_THREAD_HANDLE thread, UINT_T *watermark)
{
    // --- BEGIN: user implements ---

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Get the thread thread handle
*
* @param[out] thread: thread handle
*
* @note This API is used to get the thread handle.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_get_id(TKL_THREAD_HANDLE *thread)
{
    // --- BEGIN: user implements ---
    if (thread == NULL) {
        return OPRT_INVALID_PARM;
    }

    int *current_pid = get_cur_thread_pid();
    if (current_pid == NULL) {
        return OPRT_COM_ERROR;
    }

    *thread = (TKL_THREAD_HANDLE)current_pid;
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Set name of self thread
*
* @param[in] name: thread name
*
* @note This API is used to set name of self thread.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_set_self_name(CONST CHAR_T *name)
{
    // --- BEGIN: user implements ---
    // if (!name) {
    //     return OPRT_INVALID_PARM;
    // }
    printf("set self name");
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Check thread is self thread
*
* @param[in] thread: thread handle
* @param[out] is_self: is self thread or not
*
* @note This API is used to check thread is self thread.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_is_self(TKL_THREAD_HANDLE thread, BOOL_T *is_self)
{
    // --- BEGIN: user implements ---
    printf("tkl thread is self");

    if (thread == NULL || is_self == NULL) {
        return OPRT_INVALID_PARM;
    }

    int *current_pid = get_cur_thread_pid();
    if (current_pid == NULL) {
        return OPRT_COM_ERROR;
    }

    int *target_pid = (int *)thread;

    *is_self = (*current_pid == *target_pid) ? 1 : 0;
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Get thread priority
*
* @param[in] thread: thread handle, If NULL indicates the current thread
* @param[in] priority: thread priority
*
* @note This API is used to get thread priority.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_get_priority(TKL_THREAD_HANDLE thread, INT_T *priority)
{
    // --- BEGIN: user implements ---
    // if (NULL == thread || NULL == priority) {
    //     return OPRT_INVALID_PARM;
    // }

    printf("into tkl get pri");
    *priority = os_current_task_prio();
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Set thread priority
*
* @param[in] thread: thread handle, If NULL indicates the current thread
* @param[in] priority: thread priority
*
* @note This API is used to Set thread priority.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_set_priority(TKL_THREAD_HANDLE thread, INT_T priority)
{
    // --- BEGIN: user implements ---
    // if (NULL == thread) {
    //     return OPRT_INVALID_PARM;
    // }
    printf("tkl_thread_set_priority");
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Diagnose the thread(dump task stack, etc.)
*
* @param[in] thread: thread handle
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_thread_diagnose(TKL_THREAD_HANDLE thread)
{
    // --- BEGIN: user implements ---
    return OPRT_OK;
    // --- END: user implements ---
}

