/**
 * @file tkl_semaphore.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_semaphore.h"
#include "tuya_error_code.h"
#include "os_api.h"

typedef struct {
    OS_SEM sem;
} SEM_MANAGE, *P_SEM_MANAGE;


static TKL_SEM_HANDLE CreateSemaphore(void)
{
    P_SEM_MANAGE pSemManage;

    pSemManage = (P_SEM_MANAGE)tkl_system_malloc(sizeof(SEM_MANAGE));

    return (TKL_SEM_HANDLE)pSemManage;
}

static int InitSemaphore(const TKL_SEM_HANDLE semHandle, const unsigned int semCnt, \
                         const unsigned int sem_max)
{
    if (!semHandle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    P_SEM_MANAGE pSemManage;
    pSemManage = (P_SEM_MANAGE)semHandle;

    if (0 != os_sem_create(&pSemManage->sem, semCnt)) {
        return OPRT_OS_ADAPTER_SEM_CREAT_FAILED;
    }
    return OPRT_OK;
}
// --- END: user defines and implements ---

/**
* @brief Create semaphore
*
* @param[out] handle: semaphore handle
* @param[in] sem_cnt: semaphore init count
* @param[in] sem_max: semaphore max count
*
* @note This API is used for creating semaphore.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_semaphore_create_init(TKL_SEM_HANDLE *handle, UINT_T sem_cnt, UINT_T sem_max)
{
    // --- BEGIN: user implements ---
//    printf("创建 sem！");
    if (NULL == handle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    *handle = CreateSemaphore();
    if (*handle == NULL) {
        return OPRT_OS_ADAPTER_MALLOC_FAILED;
    }

    int ret = InitSemaphore(*handle, sem_cnt, sem_max);
    if (ret != OPRT_OK) {
        tkl_system_free(*handle);
        *handle = NULL;
        return ret;
    }
//    printf("=======tkl_semaphore_create_init handle:%p\r\n", *handle);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Wait semaphore
*
* @param[in] handle: semaphore handle
* @param[in] timeout: wait timeout, bet: ms. SEM_WAIT_FOREVER means wait until get semaphore
*
* @note This API is used for waiting semaphore.
*
* @return OPRT_OK on success.OPRT_OS_ADAPTER_SEM_WAIT_TIMEOUT means timeout. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_semaphore_wait(CONST TKL_SEM_HANDLE handle, UINT_T timeout)
{
    // --- BEGIN: user implements ---

    if (!handle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    P_SEM_MANAGE pSemManage;
    pSemManage = (P_SEM_MANAGE)handle;

    int ret;
    if (timeout == TKL_SEM_WAIT_FOREVER) {
        ret = os_sem_pend(&pSemManage->sem, 0);
    } else {
        ret = os_sem_pend(&pSemManage->sem, timeout);
    }
    if (0 != ret) {
        return OPRT_OS_ADAPTER_SEM_WAIT_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Post semaphore
*
* @param[in] handle: semaphore handle
*
* @note This API is used for posting semaphore.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_semaphore_post(CONST TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
    // signed portBASE_TYPE xHigherPriorityTaskWoken;
    if (!handle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    P_SEM_MANAGE pSemManage;
    pSemManage = (P_SEM_MANAGE)handle;

    int ret;
    ret = os_sem_post(&pSemManage->sem);

    if (0 != ret) {
        return OPRT_OS_ADAPTER_SEM_POST_FAILED;
    }
    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief Release semaphore
*
* @param[in] handle: semaphore handle
*
* @note This API is used for releasing semaphore.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_semaphore_release(CONST TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
    if (!handle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    P_SEM_MANAGE pSemManage;
    pSemManage = (P_SEM_MANAGE)handle;
    os_sem_del(&pSemManage->sem, OS_DEL_ALWAYS);
    tkl_system_free(handle); // 释放信号量管理结构

    return OPRT_OK;
    // --- END: user implements ---
}

