/**
 * @file tkl_bluetooth_bredr.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_bluetooth_bredr.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/***********************************************************************
 ********************* function ****************************************
 **********************************************************************/



/**
 * @brief   Init the Bluetooth BR-EDR Interface.
 * @param   [in] role: Init the bt bredr role;
 *          [in] p_event: register callback;
 *          [in] user_data: Init the user data;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_init(TUYA_BT_BREDR_ROLE_E role, TUYA_BT_BREDR_EVT_FUNC_CB p_event, VOID_T *user_data)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief   De-Init the Bluetooth BR-EDR Interface.
 * @param   [in] role: De-init the bt bredr role;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_deinit(TUYA_BT_BREDR_ROLE_E role)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Reset the Bluetooth BR-EDR Interface.
 * @param   [in] role: Reset the bt bredr role;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_reset(TUYA_BT_BREDR_ROLE_E role)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Set the Bluetooth BR-EDR pair mode Interface.
 * @param   [in] pair: Bluetooth BR-EDR pair mode;
 *          [in] user_data: Init the user data;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_pair_set(TUYA_BT_PAIR_INIT_PARAM_T pair)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Enable the Bluetooth BR-EDR Interface.
 * @param   [in] mode: see TUYA_BT_SCAN_MODE_E
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_enable(TUYA_BT_SCAN_MODE_E mode)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Enable the Bluetooth BR-EDR Interface.
 * @param   [in] enable: TRUE: Enable the bluetooth bredr page.
 *                       FALSE: Disable the bluetooth bredr page.
 *          [in] peer_addr: peer address for device which should be paging. if is NULL, will page the last device
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_page_enable(BOOL_T enable, TUYA_BT_GAP_ADDR_T *p_peer_addr)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Enable the Bluetooth BR-EDR Interface.
 * @param   [in] enable: TRUE: Enable the bluetooth bredr inquiry.
 *                       FALSE: Disable the bluetooth bredr inquiry.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_inquiry_enable(BOOL_T enable)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Set the BT Address
 * @param   [in] p_peer_addr: set peer address for BT;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_address_set(TUYA_BT_GAP_ADDR_T CONST *p_peer_addr)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Get the BT Address
 * @param   [out] p_peer_addr: get peer address for BT;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_address_get(TUYA_BT_GAP_ADDR_T *p_peer_addr)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Set the BT GAP Name
 * @param   [in] p_peer_addr: set local bluetooth gap name for BT;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_name_set(CHAR_T *name)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Get the BT GAP Name
 * @param   [in] p_peer_addr: get local bluetooth gap name for BT;
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_name_get(CHAR_T *name)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Request the pair while in BT-Master Mode.
 * @param   [in] mode: request security pairing mode for BT;
 *          [in] bond_info: post the major information for pairing.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_paring_request(TUYA_BT_PAIR_DEVICE_T *p_device)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Send paring passkey when in keyboard mode.
 * @param   [in] passkey: eg: 0x0001E240 means the passkey is 123456
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_paring_passkey_send(UINT_T passkey)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Enable or Disable pair when pairing request
 * @param   [in] en: TRUE for enable and FALSE for disable pair
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_paring_enable_send(BOOL_T en)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Delete the pair informations.
 * @param   [in] bond_info: delete the bond info.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_paring_delete(TUYA_BT_PAIR_BOND_INFO_T *bond_info)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   check if device is paired
 * @param   [in] NULL
 *
 * @return  TRUE
 *          FALSE
 * */
BOOL_T tkl_bt_pairing_status_get(VOID_T)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief   disconnect the link.
 * @param   [in] bond_info: disconnect the bond info.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_gap_disconnect(TUYA_BT_PAIR_BOND_INFO_T *bond_info)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Control the audio or phone, please refer to @TUYA_BT_BREDR_CONTROL_E.
 * @param   [in] crtl_event: control operations.
 *          [in] user_data: post the user-data for audio-control.
 *          [in] data_len: post the user-data length for audio-control.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_control(TUYA_BT_BREDR_CONTROL_E crtl_event, UCHAR_T *user_data, USHORT_T data_len)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Control the bredr eq
 * @param   [in] eq_mode: control equalizer mode.
 *          [in] eq_data: post the eq-data for eq.
 *          [in] eq_data_len: post the eq-data length for eq.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_equalizer_set(UCHAR_T eq_mode, UCHAR_T *eq_data, USHORT_T eq_data_len)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Swicth the bredr eq mode
 * @param   [in] eq_mode: Switch equalizer mode.
 *          [in] enable: Enable the current mode or not
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_equalizer_switch(UCHAR_T eq_mode, BOOL_T enable)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Control the bredr noise
 * @param   [in] noise_mode: control noise mode.
 *          [in] noise_data: post the noise data.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_noise_set(UCHAR_T noise_mode, USHORT_T noise_data)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Swicth the bredr noise mode
 * @param   [in] noise_mode: Switch noise mode.
 *          [in] enable: Enable the current mode or not
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_bt_bredr_noise_switch(UCHAR_T noise_mode, BOOL_T enable)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

