/**
 * @file tkl_bluetooth_sm.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_bluetooth_sm.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief   [Optional][SM Required] Init the Security Manager And Post The Correct Parameters
 *
 * @param   [in] p_security_parameter   the pointer of security parameters.
 * @return  SUCCESS
 *          ERROR   Must have either IO capabilities or OOB if MITM.
 * */
OPERATE_RET tkl_ble_security_manager_init(TUYA_BLE_SM_PARAMS_T CONST *p_security_parameter)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional][SM Required] Register the Callback While Using Security Manager.
 *
 * @param   [in] security_callback      the callback of security event, @ref TUYA_BLE_SM_PARAMS_EVT_T
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_security_callback_register(CONST TUYA_BLE_SM_FUNC_CB security_callback)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional][SM Required][Ble Peripheral/Central] Security Request, Function For Initiate the GAP Authentication procedure.
 * In the central role, this function will send an SMP Pairing Request (or an SMP Pairing Failed if rejected),
 * Otherwise in the peripheral role, an SMP Security Request will be sent.
 *
 * @param   [in] conn_handle    Connection handle.
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_security_request(USHORT_T conn_handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional][Ble Central] Encryption Request, Function For Initiate GAP Encryption procedure
 * In the central role, this function will initiate the encryption procedure using the encryption information provided.
 *
 * @param   [in] conn_handle    Connection handle.
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_encryption_request(USHORT_T conn_handle)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional][SM Required][Ble Peripheral] Reply with an authentication key. Function Using During Authentication Procedures
 * Check the Key Type During Repling the info, if key_type = 0 @def TUYA_BLE_SM_AUTH_KEY , Will Reject this Auth Request
 *
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] key_type       key type for this event @ref TUYA_BLE_SM_AUTH_KEY_REQUEST+ @param request_key_type
 * @param   [in] p_key          If key type is @ref TUYA_BLE_SM_AUTH_KEY_TYPE_NONE, then NULL.
 *                              If key type is @ref TUYA_BLE_SM_AUTH_KEY_TYPE_PASSKEY, then a 6-byte ASCII string (digit 0..9 only, no NULL termination)
 *                              or NULL when confirming LE Secure Connections Numeric Comparison.
 *                              If key type is @ref TUYA_BLE_SM_AUTH_KEY_TYPE_OOB, then a 16-byte OOB key value in little-endian format.
 * @return  SUCCESS
 *          ERROR
 * @note    Please Check the key_type and p_key, will reject this procedure if key_type = TUYA_BLE_SM_AUTH_KEY_TYPE_NONE or p_key = NULL
 *
 * */
OPERATE_RET tkl_ble_security_key_reply(USHORT_T conn_handle, UINT8_T key_type, UINT8_T CONST *p_key)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional] Get the Bonding Information.
 *
 * @param   [in] peer_index     The Peer Index for bonding information.
 * @param   [out] p_info_get    The information for one peer.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_security_info_get(TUYA_BLE_SM_SOURCE_ID_T *source_id, TUYA_BLE_SM_INFO_PARAM_T *p_info_get)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Optional] Delete the Bonding Information.
 *
 * @param   [in] peer_index     The Peer Index for bonding information.
 *
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_security_info_delete(TUYA_BLE_SM_SOURCE_ID_T *source_id)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

