/**
 * @file tkl_memory.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_memory.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/** this api was removed from kernel **/
VOID_T *tkl_system_malloc(SIZE_T size)
{
    // --- BEGIN: user implements ---
    return malloc(size);
    // --- END: user implements ---
}

/** this api was removed from kernel **/
VOID_T tkl_system_free(VOID_T *ptr)
{
    // --- BEGIN: user implements ---
    // printf("----------------------%s---------------%x\n",__func__,ptr);
    if (ptr) {
        free(ptr);
    }
    // printf("exit tkl_system_free\n");
    return;
    // --- END: user implements ---
}

/** this api was removed from kernel **/
VOID_T *tkl_system_calloc(size_t nitems, size_t size)
{
    // --- BEGIN: user implements ---
    return calloc(nitems, size);
    // --- END: user implements ---
}

/** this api was removed from kernel **/
VOID_T *tkl_system_realloc(VOID_T *ptr, size_t size)
{
    // --- BEGIN: user implements ---
    return realloc(ptr, size);
    // --- END: user implements ---
}

/** this api was removed from kernel **/
INT_T tkl_system_get_free_heap_size(VOID_T)
{
    // --- BEGIN: user implements ---
    return (INT_T)xPortGetFreeHeapSize();
    // --- END: user implements ---
}

TUYA_WEAK_ATTRIBUTE VOID_T *tkl_system_memset(VOID_T *src, INT_T ch, CONST SIZE_T n)
{
    printf("tkl_system_memset");
}

