/**
 * @file tkl_wifi_hostap.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_wifi_hostap.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief set ioctl commands to wlan driver for tuyaos wifi connection.
 * @param[in]       dev         number of sockt fd
 * @param[in]       vif_index   virtual interface index
 * @param[in]       cmd         ioctl command number
 * @param[in]       arg         ioctl parameters pointer
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_hostap_ioctl_inet(INT_T dev, INT_T vif_index, UINT_T cmd, ULONG_T arg)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

